language: node_js
node_js:
- 6.9.1
notifications:
- marcosarturjr@gmail.com

before_install:
- npm install -g bower
- npm install -g grunt-cli
- npm install -g karma-cli
- npm install -g protractor
- webdriver-manager update
- bower install

before_script:
- grunt
- cd dist
